- name: Demo on filters
  hosts: localhost
  tasks:
    - name: print no of users
      ansible.builtin.shell: uptime
      register: OUT
      
    - name: Printing numbers of users
      ansible.builtin.debug:
       msg: "{{ OUT }}"

       