    - name: Installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Copying expense conf file
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
     
    - name: Importing app pre requisites
      ansible.builtin.import_role:
       name: common
       tasks_from: app-prereq
      vars:
       app_dir: /usr/share/nginx/html
       component: frontend

    - name: Starting nginx server
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: Imporing elk role
      ansible.builtin.import_role:
       name: elk
       tasks_from: filebeat

    - name: importing node-exporter file
      ansible.builtin.import_role:
       name: prometheus
       tasks_from: node-exporter

    - name: importing grafana file
      ansible.builtin.import_role:
       name: grafana

    - name: Generate alert yml file
      ansible.builtin.template:
       src: alert-rules.yml
       dest: /tmp/{{component}}-{{env}}.yml
         
    - name: Upload alert file into S3 
      ansible.builtin.shell: aws s3 cp /tmp/{{component}}-{{env}}.yml s3://d76-prometheus-alert-rule/{{component}}-{{env}}.yml
    #  amazon.aws.s3_object:
      # bucket: d76-prometheus-alert-rule
      # object: "{{component}}-{{env}}.yml"
      # src: /tmp/{{component}}-{{env}}.yml
      # mode: put
      # permission: bucket-owner-full-control

    - name: trigger prometheus alert job role
      ansible.builtin.shell: curl -u {{ lookup ( 'amazon.aws.aws_ssm', 'jenkins.username', region='us-east-1' ) }}:{{ lookup ( 'amazon.aws.aws_ssm', 'jenkins.password', region='us-east-1' ) }} "http://172.31.40.166:8080/job/prometheus-reload/build?token=prometheus"

       
    

  

    

    