    - name: Installing nginx
      ansible.builtin.dnf:
       name: nginx
       state: present

    - name: Copying expense conf file
      ansible.builtin.template:
       src: expense.conf
       dest: /etc/nginx/default.d/expense.conf
     
    - name: Importing app pre requisites
      ansible.builtin.import_role:
       name: common
       tasks_from: app-prereq
      vars:
       app_dir: /usr/share/nginx/html
       component: frontend

    - name: Starting nginx server
      ansible.builtin.systemd:
       name: nginx
       state: restarted
       enabled: yes
    
 #   - name: Imporing elk role
  #      ansible.builtin.import_role:
   #      name: elk
   #      tasks_from: filebeat

    #  - name: importing node-exporter file
     #   ansible.builtin.import_role:
     #    name: prometheus
      #   tasks_from: node-exporter

   #   - name: importing grafana file
    #    ansible.builtin.import_role:
     #    name: grafana

     # - name: Import prometheus alert-rule-update.yml  
     #   ansible.builtin.import_role:
      #   name: prometheus
      #   tasks_from: alert-rule-update 

    - name: Install newrelic agent
      ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=NRAK-Z25QTKTTIZPRI7T2MDIRQXA6H93 NEW_RELIC_ACCOUNT_ID=4274147 /usr/local/bin/newrelic install -n infrastructure-agent-installer --tag frontend
    
    - name: Install Newrelic nginx agent 
      ansible.builtin.dnf:
       name: nri-nginx
       state: installed

    - name: Copy newrelic nginx config file
      ansible.builtin.template:
       src: nr-nginx.yml
       dest: /etc/newrelic-infra/integrations.d/nginx-config.yml

    - name: Copy newrelic nginx log shipping config file
      ansible.builtin.template:
       src: nr-nginx-log.yml
       dest: /etc/newrelic-infra/logging.d/nginx-log.yml


       
    

  

    

    