   -  name: Deleting old nginx content
      ansible.builtin.file:
       name: "{{ app_dir }}"
       state: absent

   -  name: Creating  nginx directory
      ansible.builtin.file:
       name: "{{ app_dir }}"
       state: directory
       owner: "{{app_user}}"
       group: "{{app_user}}"

   #-  name: Downlaoding and extracting content
    #  ansible.builtin.unarchive:
     #  src: https://expense-artifacts.s3.amazonaws.com/{{component}}.zip 
     #  dest: "{{ app_dir }}"
      # remote_src: yes
       
       #http://artifactory.sbadiger93.online:8081/artifactory/expense-backend/expense-backend-1.0.0.zip

   -  name: Downlaoding and extracting content
      ansible.builtin.unarchive:
       src: http://{{username}}:{{password}}@artifactory.sbadiger93.online:8081/artifactory/{{project_name}}-{{component}}/{{project_name}}-{{component}}-{{varsion}}.zip
       dest: "{{ app_dir }}"
       remote_src: yes
      vars:
       username: "{{ lookup ( 'amazon.aws.aws_ssm', 'artifactory.username', region='us-east-1' ) }}"
       password: "{{ lookup ( 'amazon.aws.aws_ssm', 'artifactory.password', region='us-east-1' ) }}"
       varsion: "{{ lookup ( 'amazon.aws.aws_ssm', '{{env}}.{{component}}.app_version', region='us-east-1' ) }}"