- name: COPYING REPO FILE
  ansible.builtin.template:
   src: filebeat
   dest: /etc/yum.repos.d/elastic.repo

- name: INSTALLING FILEBEAT
  ansible.builtin.dnf:
   name: filebeat
   state: installed

