    - name: Installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Copying expense conf file
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
     
    - name: Importing app pre requisites
      ansible.builtin.import_role:
       name: common
       tasks_from: app-prereq
      vars:
       app_dir: /usr/share/nginx/html
       component: frontend

    - name: Starting nginx server
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes