format_version: 10
pipelines:
  test-job:
    group: defaultGroup
    materials:
      deploy:
        git: https://github.com/shreebadiger/ansi.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - dev:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo 
                arguments:
                 - "Deploying to Dev env"
                run_if: passed

    - qa:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
        type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo 
                arguments:
                 - "Deploying to QA env"
                run_if: passed

    - uat:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
        type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo 
                arguments:
                 - "Deploying to UAT env"
                run_if: passed

    - prod:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
        type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo 
                arguments:
                 - "Deploying to PROD env"
                run_if: passed