- name: Copying prometheus configuration file
  ansible.builtin.template:
   src: node-exporter.yml
   dest: /opt/prometheus/node-exporter.yml

- name: Restarting prometheus
  ansible.builtin.systemd:
   name: node-exporter
   state: restarted
   enabled: yes
  