- name: Disable nodejs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs:18 -y
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Installig nodejs 
  ansible.builtin.dnf:
   name: nodejs
   state: present

- name: Copy backend service
  ansible.builtin.copy:
   src: backend.service
   dest: /etc/systemd/system/backend.service

- name: Add application user
  ansible.builtin.user:
   name: expense

- name: Importing app pre requisites
  ansible.builtin.import_role:
   name: common
   tasks_from: app-prereq
  vars:
   app_dir: /app
   component: backend

- name: Installing nodejs dependencies
  ansible.builtin.shell: npm install    
  args:
   chdir: /app
   

- name: Install mysql client
  ansible.builtin.dnf:
   name: mysql
   state: present

- name: load the schema
  ansible.builtin.shell: mysql -h mysql-dev.sbadiger93.online	 -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql 

- name: Starting mysql backend service
  ansible.builtin.systemd:
   name: backend
   state: restarted
   enabled: yes
   daemon-reload: yes