route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'SNS'
receivers:
  - name: SNS
    sns_configs:
    - sigv4:
        region: us-east-1
      topic_arn: arn:aws:sns:us-east-1:751177946459:email1:8cbc9433-1215-4de9-93df-c9a9755fc88d
      subject: prometheus alert
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
