groups:
- name: {{ component }}- {{env}}
  rules:
  - alert: CPUUsage Warning
    expr: avg by (instance) ((1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
    for: 1m
    labels:
      severity: warning
      component: {{ component }}
      env: {{ env }}
    annotations:
      summary: warning | cpu usage alert


  - alert: CPUUsage alert critical
    expr: avg by (instance) ((1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
    for: 1m
    labels:
      severity: warning
      component: {{ component }}
      env: {{ env }}
    annotations:
      summary: critical | cpu usage alert


  - alert: MemoryUsage warning
    expr: ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes ) / node_memory_MemTotal_bytes ) * 100 > 70
    for: 1m
    labels:
      severity: warning
      component: {{ component }}
      env: {{ env }}
    annotations:
      summary: warning | memory usage alert


  - alert: MemoryUsage critical
    expr: ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes ) / node_memory_MemTotal_bytes ) * 100 > 90
    for: 1m
    labels:
      severity: critical
      component: {{ component }}
      env: {{ env }}
    annotations:
      summary: critical | memory usage alert

  
